name: Build branch

env:
  GITHUB_IMAGE_NAME: ghcr.io/bp3/wm-extract-deploy

on:
  pull_request:
  workflow_dispatch:

jobs:
  call-workflow-build-image:
    uses: ./.github/workflows/build-image.yaml
    with:
      username: ${{ github.actor }}
      image-name: ghcr.io/bp3/wm-extract-deploy
      branch-name: ${{ github.head_ref || github.ref_name }}
    secrets: inherit

  run-integration-tests:
    name: Run Integration tests
    permissions:
      contents: read
      packages: read
      #pull-requests: write
    runs-on: ubuntu-latest
    needs: call-workflow-build-image
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose libxml2-utils

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pre-fetch the images we want to use
        run: integration-tests/load-images.sh

      - name: Pull image to test
        run: docker pull $GITHUB_IMAGE_NAME:${{ github.head_ref || github.ref_name }}

      - name: Run extract tests
        run: integration-tests/test-runner.sh ${{ github.head_ref || github.ref_name }} extract-compose.yaml

      - name: Run deploy tests
        run: integration-tests/test-runner.sh ${{ github.head_ref || github.ref_name }} deploy-compose.yaml
