name: Build branch

env:
  GITHUB_IMAGE_NAME: ghcr.io/bp3/wm-extract-deploy

on:
  pull_request:
  workflow_dispatch:

jobs:
  call-workflow-build-image:
    uses: ./.github/workflows/build-image.yaml

  run-extract-tests:
    name: Extract Stack
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose libxml2-utils

      - name: Run extract tests
        run: integration-tests/test-runner.sh
