name: Build branch

env:
  GITHUB_IMAGE_NAME: ghcr.io/bp3/wm-extract-deploy

on:
  pull_request:
  workflow_dispatch:

jobs:
  call-workflow-build-image:
    uses: ./.github/workflows/build-image.yaml
    with:
      username: ${{ github.actor }}
      image-name: ghcr.io/bp3/wm-extract-deploy
      branch-name: ${{ github.head_ref || github.ref_name }}
    secrets: inherit

  run-extract-tests:
    name: Extract Stack
    runs-on: ubuntu-latest
    needs: call-workflow-build-image
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose libxml2-utils

      - name: Pre-fetch the images we want to use
        run: RUNDIR=$PWD integration-tests/load-images.sh extract-compose.yaml

      - name: Run extract tests
        run: RUNDIR=$PWD integration-tests/test-runner.sh ${{ github.head_ref || github.ref_name }} extract-compose.yaml
