name: Build main

env:
  GITHUB_IMAGE_NAME: ghcr.io/bp3/wm-extract-deploy

on:
  push:
    branches:
      - main
    paths-ignore:
      - integration-tests
      - files
  workflow_dispatch:

jobs:
  call-workflow-build-image:
    uses: ./.github/workflows/build-image.yaml
    with:
      username: ${{ github.actor }}
      image-name: ${{ env.GITHUB_IMAGE_NAME }}
      branch-name: ${{ env.GITHUB_REF_NAME }}
    secrets: inherit
