name: Release Pipeline

env:
  DOCKER_IMAGE_NAME: "bp3global/wm-extract-deploy"

on:
  release:
    types:
      - published
  workflow_dispatch

jobs:
  release:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      # Build the docker image and apply the tag
      - name: Build Docker image of application
        run: |
          docker build -t $DOCKER_IMAGE_NAME:$GITHUB_REF_NAME .

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: "bp3docker"
          password: ${{ secrets.DOCKERHUB_BP3DOCKER }}

      # Push the image both as 'tag' and 'latest'
      - name: Push Docker image to Docker Hub
        run: |
          docker push $DOCKER_IMAGE_NAME:$GITHUB_REF_NAME
          docker tag $DOCKER_IMAGE_NAME:$GITHUB_REF_NAME $DOCKER_IMAGE_NAME:latest
          docker push $DOCKER_IMAGE_NAME:latest
